# Generated by Django 3.2.8 on 2021-10-31 12:40

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=150)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('sub_title', models.TextField()),
                ('news_image', models.ImageField(max_length=259, upload_to='news/')),
                ('news_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='news_title')),
            ],
        ),
    ]
