# Generated by Django 3.2.8 on 2021-11-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspostmodel',
            name='newsCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news_category'),
        ),
    ]
